language: php

php:
# pekkis/mime-types v1.0.0 requires php >=5.5.0
- 7.0
- 7.1

services:
- memcached
- redis

install:
- travis_retry composer require "satooshi/php-coveralls" "^1" --dev --no-update
- travis_retry composer install
# - ./travis/install-apcu
- ./travis/install-cssmin
- ./travis/install-yaml

before_script:
- phpenv config-add travis/config/$TRAVIS_PHP_VERSION.ini
- phpenv config-add travis/config/apc.ini
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- phpenv rehash
- cp -v config/framework.dev.yml config/framework.yml
- cp -v config/database.dev.yml config/database.yml
- mkdir -p app cache bundles
- rm -f bootstrap.php
script:
- php bin/phifty bootstrap
- time php bootstrap.php
- phpunit -c phpunit.xml.dist

after_success:
- php vendor/bin/coveralls -v

cache:
  apt: true
  directories:
  - vendor
