language: php

php:
- 7.0
- 7.1

services:
- memcached
- redis

install:
- travis_retry composer require "satooshi/php-coveralls" "^1" --dev --no-update
- travis_retry composer install
- "./travis/install-cssmin"
- "./travis/install-yaml"

before_script:
- phpenv config-add travis/config/$TRAVIS_PHP_VERSION.ini
- phpenv config-add travis/config/apc.ini
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- phpenv rehash
- cp -v config/framework.dev.yml config/framework.yml
- cp -v config/database.dev.yml config/database.yml
- mkdir -p app cache bundles
- rm -f bootstrap.php

script:
- php bin/phifty bootstrap
- time php bootstrap.php
- phpunit -c phpunit.xml.dist

after_success:
- php vendor/bin/coveralls -v

cache:
  apt: true
  directories:
  - vendor

notifications:
  email:
    on_success: change # default: always
    on_failure: change # default: always
  slack:
    secure: G/7MNT2ZQirPcxX4ui1qn7mfDi29FPIY1ThN4c+KMp5IMLoFtHmrs+3hdCXLQC4mYkWrqLQVQpqRZb92qemZAbRpyaV+1g6IDFzunia95aF2eDRD73TQCNDrKkxhBi69FGo3ToOiB1wTtX/WYLFfkfOmFI43Wu+5fTmvH2mOtIk=
    on_success: always # default: always
    on_failure: always # default: always
