language: php

php:
- "5.6"
- "7.0"
- "7.1"
- "hhvm"

matrix:
  fast_finish: true
  allow_failures:
  - php: "hhvm"
  - php: "5.6"

services:
- memcached
- redis
- postgresql
- mysql

install:
- composer require "satooshi/php-coveralls" "^1" --no-update --dev
- composer install
- ./travis/install

before_script:
# install and setup apache2
- sudo apt-get install apache2 libapache2-mod-fastcgi
- sudo a2enmod rewrite actions fastcgi alias
- echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
- cat travis/apache2/php.conf | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
- cat travis/apache2/site.conf | sed -e "s,%TRAVIS_BUILD_DIR%,`pwd`/webroot,g" | sudo tee /etc/apache2/sites-available/default > /dev/null

# enable php-fpm
- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
# - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

# restart to reload apache2
- sudo service apache2 restart

- phpenv rehash
- ./travis/before_script
- cp -v config/framework.dev.yml config/framework.yml
- cp -v config/database.dev.yml config/database.yml

script:
- ./travis/bootstrap
- time php bootstrap.php
- wc -l bootstrap.php
- php bin/phifty asset --link
- phpunit -c phpunit.xml.dist
- curl http://localhost/

after_success:
- php vendor/bin/coveralls -v

cache:
  apt: true
  directories:
  - vendor
  - ~/.composer/cache

notifications:
  email:
    on_success: change # default: always
    on_failure: change # default: always
  slack:
    secure: G/7MNT2ZQirPcxX4ui1qn7mfDi29FPIY1ThN4c+KMp5IMLoFtHmrs+3hdCXLQC4mYkWrqLQVQpqRZb92qemZAbRpyaV+1g6IDFzunia95aF2eDRD73TQCNDrKkxhBi69FGo3ToOiB1wTtX/WYLFfkfOmFI43Wu+5fTmvH2mOtIk=
