language: php
php:
- 5.4
- 5.5
- 5.6
install:
- bash scripts/install-apcu.sh
- phpenv config-add tests/config/$TRAVIS_PHP_VERSION.ini
- phpenv config-add tests/config/apc.ini
- travis_retry composer self-update
- travis_retry composer update
before_script:
- mkdir -p app applications bundles cache
- phpenv rehash
script:
- php bin/phifty build && time php bootstrap.php
- phpunit
after_success:
cache:
  apt: true
  directories:
  - vendor
notifications:
  slack:
    secure: OwI7PtL9OGmGvwJ8SRObkTvl0cMQqRssLJ+fWwrAUQ4HW/CxAg95q0jPZ4YHmUk6eFTp23HtYrV62icVUiw0dmbGOnsKBPKW5fMs8+rXTXcKi4lu5sP8lsak8ORBLcp75pagiMrviMS6nvAJO/l0U7XMGGGHJjbfyLa5bRkXdRo=
