---
cli:
  bootstrap: 'main.php'
schema:
  auto_id: true
  loader: Phifty/SchemaLoader.php
seeds:
databases:
  master:
    driver: mysql
    host: localhost
    database: phifty
    user: root
    pass:
