---
cli:
  bootstrap: "bootstrap.php"
schema:
  auto_id: true
  finders:
  - Phifty::Schema::Finder::AppSchemaFinder
  - { name: ComposerSchemaFinder, args: ["composer.json"] }
seeds:
databases:
  master:
    driver: mysql
    host: localhost
    database: testing
    user: root
    pass:
