---
ApplicationName: MyApp
ApplicationID:   myapp
ApplicationUUID: 84dd6792-a0a4-11e4-aa35-3c15c2cb5a5a
Domain: myapp.dev
Mail:
  System: "\"System\" <noreply@localhost>"
  Admin: "\"Admin\" <admin@localhost>"
Applications:
ServiceProviders:
  BundleServiceProvider:
    Paths:
      - bundles
  DatabaseServiceProvider:
    config: config/database.yml
  CurrentUserServiceProvider:
    Class: Phifty\Security\CurrentUser
    Model: UserBundle\Model\User
  ActionServiceProvider:
  PuxRouterServiceProvider:
  LibraryServiceProvider:
  ViewServiceProvider:
  MailerServiceProvider:
    Transport: MailTransport
  CacheServiceProvider: ~
  LocaleServiceProvider:
    Directory: locale
    Default: zh_TW
    Domain: myapp
    Langs:
      - en
      - zh_TW
  CacheServiceProvider:
    APC: true
    FileSystem: true
    Memcached: true
  SessionServiceProvider:
  TwigServiceProvider:
    TemplateDirs: []
  AssetServiceProvider:
    BaseUrl: /assets
    BaseDir: webroot/assets
  PredisServiceProvider:
  RedisServiceProvider:
  AesCryptorServiceProvider:
  FirePHPServiceProvider:
Bundles:
  CoreBundle:
  CommonBundle:
  AdminUI:
  UserBundle:
    UseAccount: true
